name: localhost

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:

  CheckVarDump:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - name: Checkear si hay var_dump
          run: grep -q var_dump modelos/usuarioModelo.class.php && exit 1 || true