name: localhost

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:

  CheckSyntax:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - name: Checkear sintaxis de modelo
          run: 'find . -name *.php -exec php -l {} \;'