name: localhost

on:
  push:
    branches: [**]
  pull_request:
    branches: [**]

  workflow_dispatch:

jobs:

  CheckPrintR:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - name: Checkear si hay print_r
          run: grep -q print_r modelos/usuarioModelo.class.php && exit 1 || true