name: localhost
on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
  
jobs:
  CheckSyntax:
    runs-on: [self-hosted]
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - name: Check syntax in all php files of repo
        run: for archivo in $(find . | grep php); do  php -l $archivo || exit 1; done

  RunTestingAdmin:
    runs-on: [self-hosted]
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - name: Run testing for admin
        run: cd /home/administrador/chat-institucional/administrador/app && ../vendor/bin/phpunit ../tests/tests.php --colors

  RunTestingStudent:
    runs-on: [self-hosted]
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - name: Run testing for student
        run: cd /home/administrador/chat-institucional/alumno/app && ../vendor/bin/phpunit ../tests/tests.php --colors

  
  RunTestingTeacher:
    runs-on: [self-hosted]
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - name: Run testing for teacher
        run: cd /home/administrador/chat-institucional/profesor/app && ../vendor/bin/phpunit ../tests/tests.php --colors